services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
    networks:
      - n8n-network

  # Uncomment this section if you want to use PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n-network

  # Redis for queue management (optional, for better performance)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  data:
  files:
  # postgres_data:  # Uncomment if using PostgreSQL
  # redis_data:     # Uncomment if using Redis
